var arrows={
	f:4,
	w:16,
	h:16,
	p:
	[

	  [
      "CCCCCCCCCCCCCCCC",
      "C..............C",
      "C..............C",
      "C..............C",
      "C......CC......C",
      "C.....CCCC.....C",
      "C....CCCCCC....C",
      "C...CCCCCCCC...C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C..............C",
      "C..............C",
      "C..............C",
      "CCCCCCCCCCCCCCCC",
    ],

	  [
      "CCCCCCCCCCCCCCCC",
      "C..............C",
      "C..............C",
      "C..............C",
      "C.......C......C",
      "C.......CC.....C",
      "C...CCCCCCC....C",
      "C...CCCCCCCC...C",
      "C...CCCCCCCC...C",
      "C...CCCCCCC....C",
      "C.......CC.....C",
      "C.......C......C",
      "C..............C",
      "C..............C",
      "C..............C",
      "CCCCCCCCCCCCCCCC",
    ],

	  [
      "CCCCCCCCCCCCCCCC",
      "C..............C",
      "C..............C",
      "C..............C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C.....CCCC.....C",
      "C...CCCCCCCC...C",
      "C....CCCCCC....C",
      "C.....CCCC.....C",
      "C......CC......C",
      "C..............C",
      "C..............C",
      "C..............C",
      "CCCCCCCCCCCCCCCC",
    ],

	  [
      "CCCCCCCCCCCCCCCC",
      "C..............C",
      "C..............C",
      "C..............C",
      "C......C.......C",
      "C.....CC.......C",
      "C....CCCCCCC...C",
      "C...CCCCCCCC...C",
      "C...CCCCCCCC...C",
      "C....CCCCCCC...C",
      "C.....CC.......C",
      "C......C.......C",
      "C..............C",
      "C..............C",
      "C..............C",
      "CCCCCCCCCCCCCCCC",
    ],


	]
};

